/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "If the game tries to Download a file automatically when you open the game, please download it since it happens when you open an old SaveFile to a new version. It is design this way so if an update somehow brakes your save you automatically have a backup save.": "如果您打开游戏时游戏尝试自动下载文件，请下载该文件，因为当您将旧的保存文件打开到新版本时会发生这种情况。 它是这样设计的，因此如果更新以某种方式阻止了您的保存，您会自动拥有备份保存。",
    "and tell me.": "然后告诉我。",
    "Bosses": "Boss",
    "Clones:": "克隆：",
    "Cmon, unlock me": "来吧，解锁我",
    "Discord": "Discord",
    "Don't click me": "别点我",
    "Don't click me 2": "别点我2",
    "Export Save": "导出保存",
    "Have any questions or want to suggest stuff? Go to": "有任何疑问或想要提出建议吗？ 去",
    "I hope you have fun with the game.": "我希望你在游戏中玩得开心。",
    "Import Save": "导入保存",
    "It's Locked Boys": "小伙子，它被锁定了",
    "It's not for you today": "今天不是为了你",
    "Load": "加载",
    "MAX": "最大",
    "Menu:": "菜单：",
    "No No No...": "不不不...",
    "Pfff, you know it's fun, right?": "噗，你知道这很有趣，对吧？",
    "Pfff, You know it's fun, right?": "噗，你知道这很有趣，对吧？",
    "Player Stats:": "球员统计：",
    "Saving and Loading:": "保存和加载：",
    "Thanks for trying this game out!": "感谢您尝试这款游戏！",
    "There are some locked areas too that you unlock by beating bosses. These new Menus unlock new ways to get stronger using your clones.": "还有一些锁定的区域可以通过击败老板来解锁。 这些新菜单解锁了使用克隆体变得更强的新方法。",
    "Toggle Help Screen": "切换帮助屏幕",
    "Training": "训练",
    "Version": "版本",
    "Version 1.1": "版本1.1",
    "Welcome to Idling Master": "欢迎来到放置大师",
    "Welcome to Idling Master, on this game you have the power to multiply yourself, with that power you decide to fight the local Bosses League. Do you have what it takes to overtake the challenge?": "欢迎来到《闲置大师》，在这款游戏中，您拥有倍增自己的力量，并利用这种力量决定与当地的老板联盟作战。 您有能力应对挑战吗？",
    "Wow, I'm locked": "哇哦，我被锁定了",
    "Wow, I'm Locked": "哇哦，我被锁定了",
    "You gotta Learn...": "你必须学习...",
    "You should start by heading out to the Training Area and get stronger to defeat the bosses on the Bosses Area.": "你应该首先前往训练区并变得更强，以击败头目区的头目。",
    "Boss Menu": "Boss 菜单",
    "Defense": "防御",
    "Defense per Second:": "每秒防御：",
    "Fight": "战斗",
    "HP per Second:": "每秒生命值：",
    "HP Regen per Second:": "每秒生命恢复：",
    "Stats Gained per Second:": "每秒获得的属性：",
    "Strength": "力量",
    "Strength Per Second:": "每秒力量：",
    "You didn't take any damage, NICE!": "你没有受到任何伤害，很好！",
    "\"I heard there is this dojo in town where you can fight people for money, you can go there and fight them, we never know where the next big thing is.\"": "“我听说镇上有一个道场，你可以在那里和人打钱，你可以去那里和他们打，我们永远不知道下一件大事在哪里。”",
    "Arena Multi:": "竞技场多：",
    "Attack": "攻击",
    "Attack:": "攻击：",
    "Base:": "根据：",
    "Bounty Multi:": "赏金乘数：",
    "City Multi:": "城市乘数：",
    "Crafting Multi:": "制作乘数：",
    "Defense:": "防御：",
    "Display Multipliers": "显示乘数",
    "Dojo": "道场",
    "Dojo Multi:": "道场乘数：",
    "Dojo Stats": "道场统计",
    "Farm Multi:": "农场乘数：",
    "Farm:": "农场：",
    "HP": "生命值",
    "John, the Gardener": "园丁约翰",
    "Main Entrance": "主要入口",
    "Main Stats": "主要统计数据",
    "Mine:": "矿：",
    "Mining/Farming": "采矿/农业",
    "Misc.": "杂项",
    "On this screen you assign clones to training, there are 5 tiers of training to unlock, every tier is more efficient than the last, but takes more time": "在此屏幕上您分配克隆进行训练，有 5 层训练需要解锁，每一层都比上一层更有效率，但需要更多时间",
    "Reach Boss #5 so you can unlock the next zone!": "到达 Boss #5，即可解锁下一个区域！",
    "Regroup Multi:": "重新组合多重：",
    "Reset Save": "重置 保存",
    "Scientific Notation": "科学计数法",
    "Shady Guy": "阴暗家伙",
    "Short Number Notation": "短数字表示法",
    "Some tiers get more bonuses, like the Tier 2 defense also gives HP": "有些等级可以获得更多奖励，例如第 2 级防御也可以提供生命值",
    "Strength:": "力量：",
    "Total Arena Bosses Killed:": "竞技场首领死亡总数：",
    "Total Attack:": "总攻击力：",
    "Total Bosses Defeated:": "击败的Boss总数：",
    "Total Clones Multiplier:": "总克隆乘数：",
    "Total Contracts Finished:": "已完成合同总数：",
    "Total Crops Grown:": "农作物种植总量：",
    "Total Dojo Enemies Defeated:": "击败道场敌人总数：",
    "Total Farm Multiplier:": "农场总乘数：",
    "Total Mining Multipliers:": "总挖矿乘数：",
    "Total Ores Mined:": "开采矿石总量：",
    "Total Strenght:": "总力量:",
    "Total Time:": "总时间：",
    "Total Warehouse Rank Ups:": "仓库总排名：",
    "Warehouse Multi:": "仓库乘数：",
    "You": "你",
    "You arrive at the dojo and find there some greeting people, maybe they are some of the people that guy told you about, it's time to start kicking ass!": "你到达道场，发现那里有一些人在打招呼，也许他们就是那个家伙告诉你的人，是时候开始踢屁股了！",
    "Your Taxi Driver": "您的出租车司机",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'I',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Clones: ": "克隆: ",
    "Defense: ": "防御: ",
    "Strength: ": "力量: ",
    "Moneys: ": "金币: ",
    "Boss Attack: ": "Boss攻击力: ",
    "Boss Health: ": "Boss生命值: ",
    "HP: ": "生命值: ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    " to Next level": " 到达下一级",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^([\d\.,]+)X$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^You took (.+) damage.$/, '你受到了 $1 点伤害。'],
    [/^Eat\(Level (.+)\): (.+) clones assigned$/, '吃东西（$1 级）：分配了 $2 克隆'],
    [/^Scream\(Level (.+)\): (.+) clones assigned$/, '尖叫（$1 级）：分配了 $2 克隆'],
    [/^Punch\(Level (.+)\): (.+) clones assigned$/, '拳击（$1 级）：分配了 $2 克隆'],
    [/^Rest\(Level (.+)\): (.+) clones assigned$/, '休息（$1 级）：分配了 $2 克隆'],
    [/^The Boss took (.+) damage.$/, 'Boss 受到了 $1 点伤害。'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^Boss Number ([\d\.,]+)$/, 'Boss 数字 $1'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],
]);